#!/bin/sh

dir=$(dirname $(realpath $0))
service_dir=$dir/service
script_dir=$dir/script
program=$(basename $0)

if [ $(id -u) != 0 ]; then
	exit 1
fi

rm -rf /usr/bin/backlight

if [ -f /etc/systemd/system/backlight.load.service ]; then
	systemctl disable backlight.load
	rm -rf /etc/systemd/system/backlight.load.service
fi

if [ -f /etc/systemd/system/backlight.save.service ]; then
	systemctl disable backlight.save
	rm -rf /etc/systemd/system/backlight.save.service
fi
